### ISSUE TITLE
custom latlong datatype?

### ISSUE THREAD

**Issue by zeffii** [Marcus-Richmond/sverchok-gis-nodes#9]
https://nedbatchelder.com/blog/202204/python_custom_formatting.html

**Comment by Marcus-Richmond** [comment]
I think leaving lat/long values as float is the way to go (at least for now). There may be instances of users wanting to plot a table of points (with lat/long in degrees minutes seconds) straight into Sverchok, but I think the effort of making this available is probably better spent on other things for now. In other words, I think we can expect users to have their lat/long coordinates in decimal degrees before they attempt to work with it in Sverchok.

**Comment by zeffii** [comment]
agreed.

some of these issues will be like postit notes :)
